# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Package Build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Eslint
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint:ci
      - name: Run Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
    
      - name: Archive build dist
        if: matrix.node-version == '16.x'
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist
          
      - name: Archive examples
        if: matrix.node-version == '16.x'
        uses: actions/upload-artifact@v4
        with:
          name: build-examples
          path: examples
    # - uses: borales/actions-yarn@v2.3.0
    #   with:
    #     cmd: test

  review:
    needs: build
    permissions: write-all
    uses: ./.github/workflows/pr-viewer.yml
    # inherit the secrets from the parent workflow
    # https://docs.github.com/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
    secrets: inherit